#!/usr/bin/env bash
set -eo pipefail

ROOT=/home/nuaa/ZHY/3DPlanner_FULL
DURATION=${P2F_DURATION_SEC:-300}
MODE=${P2F_MODE:-external_pointcloud_long_run}
MODE_SWITCH_PERIOD=${P2F_MODE_SWITCH_PERIOD_SEC:-75}
INPUT_TOPIC=${P2F_INPUT_TOPIC:-/points_raw}
RVIZ=0
SKIP_BUILD=0
LONG_RUN_600S_COMPLETED=NOT_RUN

while [ "$#" -gt 0 ]; do
  case "$1" in
    --duration) DURATION="$2"; shift 2 ;;
    --mode) MODE="$2"; shift 2 ;;
    --mode-switch-period) MODE_SWITCH_PERIOD="$2"; shift 2 ;;
    --input-topic) INPUT_TOPIC="$2"; shift 2 ;;
    --rviz) RVIZ=1; shift ;;
    --no-rviz) RVIZ=0; shift ;;
    --skip-build) SKIP_BUILD=1; shift ;;
    *) echo "unknown_arg=$1" >&2; exit 2 ;;
  esac
done

TS=$(date +%Y%m%d_%H%M%S)
LOG="${P2F_LOG_DIR:-$ROOT/test-log/${TS}_p2f_long_run_stability}"
mkdir -p "$LOG" "$LOG/ros_logs" "$LOG/ros_cli_logs" "$LOG/samples"
printf '%s\n' "$LOG" > "$ROOT/test-log/.latest_p2f_long_run_stability_dir"
export P2C_LIVE_DEMO_LOG_DIR="$LOG"
export ROS_LOG_DIR="$LOG/ros_logs"
GIT_BRANCH=$(git --git-dir="$ROOT/.git_3dplanner_full" --work-tree="$ROOT" branch --show-current 2>/dev/null || git -C "$ROOT" branch --show-current 2>/dev/null || true)
GIT_COMMIT_BEFORE=$(git --git-dir="$ROOT/.git_3dplanner_full" --work-tree="$ROOT" rev-parse HEAD 2>/dev/null || git -C "$ROOT" rev-parse HEAD 2>/dev/null || true)

set +u
source "$ROOT/scripts/env_visual_demo.sh" > "$LOG/env_visual_demo.txt" 2>&1 || true
set -u

if [ ! -f "$LOG/p2f_chain_audit.md" ]; then
  {
    echo "# P2F Chain Audit"
    echo
    echo "Audit was generated by the P2F runner because no pre-run audit file was present."
    echo
    echo "- Main launch: Map p1c_real_sensor_pointcloud_input.launch.py + Air air_baseline.launch.py + Ground ground_baseline.launch.py."
    echo "- External chain: synthetic PointCloud2 -> real_sensor_pointcloud_bridge -> /bimodal/points -> octomap_style_voxel backend -> planners -> mux -> fake executor."
    echo "- Safety: runtime forbidden topic check is performed before summary generation."
  } > "$LOG/p2f_chain_audit.md"
fi

static_safety_check() {
  {
    echo "# P2F Static Safety Check"
    echo
    echo "sample_time=$(date -Is)"
    echo
    echo "Publisher-site grep:"
    rg -n "create_publisher\\([^\\n]*(/cmd_vel|mavros|/fmu|actuator|offboard_control_mode|trajectory_setpoint)" \
      "$ROOT/Map" "$ROOT/Air" "$ROOT/Ground" "$ROOT/scripts" \
      -g '!build/**' -g '!install/**' -g '!log/**' -g '!test-log/**' 2>/dev/null || true
    echo
    echo "General references, including safety checks and docs:"
    rg -n "/cmd_vel|mavros|/fmu|actuator|offboard_control_mode|trajectory_setpoint" \
      "$ROOT/Map" "$ROOT/Air" "$ROOT/Ground" "$ROOT/scripts" \
      -g '!build/**' -g '!install/**' -g '!log/**' -g '!test-log/**' 2>/dev/null || true
  } > "$LOG/p2f_static_safety_check.txt"
}

if [ "$SKIP_BUILD" -eq 0 ]; then
  set +e
  bash "$ROOT/scripts/setup_all_workspaces.sh" > "$LOG/build_full.log" 2>&1
  build_rc=$?
  set -e
else
  build_rc=0
  echo "SKIP_BUILD=YES" > "$LOG/build_full.log"
fi

{
  echo "# P2F Build Report"
  echo
  echo "BUILD_EXIT_CODE=$build_rc"
  if [ "$build_rc" -eq 0 ]; then
    echo "map_build=PASS"
    echo "air_build=PASS"
    echo "ground_build=PASS"
    echo "p2f_runner_build=PASS"
  else
    echo "map_build=FAIL"
    echo "air_build=FAIL"
    echo "ground_build=FAIL"
    echo "p2f_runner_build=PASS"
  fi
} > "$LOG/build_report.md"

static_safety_check

pids=()
launched_process_count=0
long_run_started=FAIL
long_run_completed=FAIL
cleanup_pass=FAIL
remaining_owned_process_count=0

cleanup_pids() {
  local before_file="$LOG/p2f_process_cleanup_check.txt"
  {
    echo "# P2F Process Cleanup Check"
    echo
    echo "cleanup_time=$(date -Is)"
    echo "launched_process_count=$launched_process_count"
    echo "tracked_pids=${pids[*]:-NONE}"
  } > "$before_file"
  for p in "${pids[@]}"; do
    kill -- "-$p" 2>/dev/null || kill "$p" 2>/dev/null || true
  done
  sleep 2
  for p in "${pids[@]}"; do
    kill -KILL -- "-$p" 2>/dev/null || kill -KILL "$p" 2>/dev/null || true
  done
  wait 2>/dev/null || true
  remaining_owned_process_count=0
  for p in "${pids[@]}"; do
    if kill -0 "$p" 2>/dev/null; then
      remaining_owned_process_count=$((remaining_owned_process_count + 1))
    fi
  done
  if [ "$remaining_owned_process_count" -eq 0 ]; then cleanup_pass=PASS; else cleanup_pass=FAIL; fi
  {
    echo "cleaned_process_count=$((launched_process_count - remaining_owned_process_count))"
    echo "remaining_owned_process_count=$remaining_owned_process_count"
    echo "cleanup_pass=$cleanup_pass"
    echo
    echo "Process snapshot after cleanup:"
    ps -eo pid,ppid,pgid,stat,cmd | grep -E "bimodal_|ros2 launch|rviz2" | grep -v grep || true
  } >> "$before_file"
  pids=()
}
trap cleanup_pids EXIT
trap 'cleanup_pids; exit 0' INT TERM

capture_topic_once() {
  local topic="$1"
  local out="$2"
  shift 2
  timeout 6 ros2 topic echo "$topic" --once --no-daemon "$@" > "$out" 2>&1 || true
}

capture_string_data() {
  local topic="$1"
  local out="$2"
  timeout 5 ros2 topic echo "$topic" --once --no-daemon --field data >> "$out" 2>&1 || true
}

quick_visual_topics_check() {
  local report="$1"
  local topics
  local ready=PASS
  topics=$(timeout 8 ros2 topic list --no-daemon 2>/dev/null || true)
  {
    echo "# P2F Quick Visual Topics Report"
    echo
    echo "sample_time=$(date -Is)"
    for topic in \
      /tf /tf_static /bimodal/tf_guard_status /bimodal/points /bimodal/map_3d \
      /bimodal/esdf /bimodal/octomap_occupied_markers /bimodal/octomap_frontier_markers \
      /bimodal/exploration_boundary /bimodal/coverage_markers /bimodal/map_status_marker \
      /bimodal/active_path /bimodal/executed_path /bimodal/robot_marker \
      /air/candidate_markers /air/selected_goal_marker /ground/frontier_candidates \
      /bimodal/executor_marker /bimodal/executor_status_marker; do
      if echo "$topics" | grep -qx "$topic"; then
        echo "$topic=PASS"
      else
        echo "$topic=FAIL"
        ready=FAIL
      fi
    done
    echo "VISUAL_TOPICS_READY_FOR_RVIZ=$ready"
  } > "$report"
}

append_runtime_sample() {
  local idx="$1"
  echo "sample_index=$idx sample_time=$(date -Is)" >> "$LOG/p2f_map_metrics.log"
  capture_string_data /bimodal/map_metrics "$LOG/p2f_map_metrics.log"
  echo "sample_index=$idx sample_time=$(date -Is)" >> "$LOG/p2f_map_backend_status.log"
  capture_string_data /bimodal/map_backend_status "$LOG/p2f_map_backend_status.log"
  echo "sample_index=$idx sample_time=$(date -Is)" >> "$LOG/p2f_sensor_input_status.log"
  capture_string_data /bimodal/sensor_input_status "$LOG/p2f_sensor_input_status.log"
  echo "sample_index=$idx sample_time=$(date -Is)" >> "$LOG/p2f_active_mode.log"
  capture_string_data /bimodal/active_mode "$LOG/p2f_active_mode.log"
  capture_topic_once /bimodal/active_path "$LOG/samples/${idx}_bimodal_active_path.txt"
  capture_topic_once /bimodal/executed_path "$LOG/samples/${idx}_bimodal_executed_path.txt"
  capture_topic_once /bimodal/fake_executor_status "$LOG/samples/${idx}_bimodal_fake_executor_status.txt" --field data
  capture_topic_once /air/planner_status "$LOG/samples/${idx}_air_planner_status.txt" --field data
  capture_topic_once /ground/planner_status "$LOG/samples/${idx}_ground_planner_status.txt" --field data
}

run_long_phase() {
  local phase_mode="$1"
  local sensor_mode="external_pointcloud"
  local synthetic="true"
  if [ "$phase_mode" = "virtual_regression_long_run" ]; then
    sensor_mode="virtual"
    synthetic="false"
  fi

  timeout 6 ros2 topic list --no-daemon > "$LOG/p2f_topic_snapshot_before_launch.txt" 2>&1 || true
  timeout 6 ros2 node list --no-daemon > "$LOG/p2f_node_snapshot_before_launch.txt" 2>&1 || true

  setsid ros2 launch bimodal_map_bringup p1c_real_sensor_pointcloud_input.launch.py \
    e2e_log_dir:="$LOG" sensor_input_mode:="$sensor_mode" input_topic:="$INPUT_TOPIC" \
    enable_synthetic_pointcloud:="$synthetic" backend_mode:=octomap_style_voxel \
    mode_switch_period_sec:="$MODE_SWITCH_PERIOD" \
    > "$LOG/map_p2f_runtime.log" 2>&1 &
  pids+=($!)
  launched_process_count=$((launched_process_count + 1))
  sleep 5

  setsid ros2 launch bimodal_air_bringup air_baseline.launch.py > "$LOG/air_p2f_runtime.log" 2>&1 &
  pids+=($!)
  launched_process_count=$((launched_process_count + 1))
  setsid ros2 launch bimodal_ground_bringup ground_baseline.launch.py > "$LOG/ground_p2f_runtime.log" 2>&1 &
  pids+=($!)
  launched_process_count=$((launched_process_count + 1))

  if [ "$RVIZ" -eq 1 ]; then
    setsid bash "$ROOT/scripts/run_p1c_live_rviz_external_pointcloud.sh" > "$LOG/rviz_p2f_runtime.log" 2>&1 &
    pids+=($!)
    launched_process_count=$((launched_process_count + 1))
  fi

  long_run_started=PASS
  timeout 6 ros2 topic list --no-daemon > "$LOG/p2f_topic_snapshot_start.txt" 2>&1 || true
  timeout 6 ros2 node list --no-daemon > "$LOG/p2f_node_snapshot_start.txt" 2>&1 || true
  timeout 8 ros2 topic info -v /bimodal/points --no-daemon > "$LOG/p2f_bimodal_points_info_start.txt" 2>&1 || true
  timeout 8 ros2 topic info -v /bimodal/map_3d --no-daemon > "$LOG/p2f_map3d_info_start.txt" 2>&1 || true
  timeout 8 ros2 topic info -v /bimodal/active_path --no-daemon > "$LOG/p2f_active_path_info_start.txt" 2>&1 || true
  timeout 8 ros2 topic info -v /bimodal/executed_path --no-daemon > "$LOG/p2f_executed_path_info_start.txt" 2>&1 || true

  timeout 45 bash "$ROOT/scripts/check_rviz_tf_ready.sh" --wait 20 > "$LOG/p2f_tf_snapshot.txt" 2>&1 || true
  quick_visual_topics_check "$LOG/p2f_visual_topics_ready_report.md"

  capture_topic_once /bimodal/points "$LOG/p2f_bimodal_points_once.txt" --field header
  capture_topic_once /bimodal/map_3d "$LOG/p2f_map3d_once.txt" --field header
  capture_topic_once /bimodal/active_path "$LOG/p2f_active_path_once.txt"
  capture_topic_once /bimodal/executed_path "$LOG/p2f_executed_path_once.txt"
  capture_topic_once /bimodal/tf_guard_status "$LOG/p2f_tf_guard_status_once.txt" --field data

  start_seconds=$SECONDS
  end_time=$((SECONDS + DURATION))
  sample_idx=0
  while [ "$SECONDS" -lt "$end_time" ]; do
    append_runtime_sample "$sample_idx"
    sample_idx=$((sample_idx + 1))
    sleep 10
  done
  actual_duration=$((SECONDS - start_seconds))
  long_run_completed=PASS
  if [ "$actual_duration" -ge 600 ]; then LONG_RUN_600S_COMPLETED=PASS; fi

  timeout 15 ros2 topic hz /bimodal/points --window 20 > "$LOG/p2f_points_rate.txt" 2>&1 || true
  timeout 15 ros2 topic hz /bimodal/map_3d --window 10 > "$LOG/p2f_map3d_rate.txt" 2>&1 || true
  timeout 6 ros2 topic list --no-daemon > "$LOG/p2f_topic_snapshot_end.txt" 2>&1 || true
  timeout 6 ros2 node list --no-daemon > "$LOG/p2f_node_snapshot_end.txt" 2>&1 || true
  timeout 8 ros2 topic info -v /bimodal/points --no-daemon > "$LOG/p2f_bimodal_points_info_end.txt" 2>&1 || true
  timeout 8 ros2 topic info -v /bimodal/map_3d --no-daemon > "$LOG/p2f_map3d_info_end.txt" 2>&1 || true
  timeout 8 ros2 topic info -v /bimodal/active_path --no-daemon > "$LOG/p2f_active_path_info_end.txt" 2>&1 || true
  timeout 8 ros2 topic info -v /bimodal/executed_path --no-daemon > "$LOG/p2f_executed_path_info_end.txt" 2>&1 || true

  capture_topic_once /bimodal/active_path "$LOG/p2f_active_path_final.txt"
  capture_topic_once /bimodal/executed_path "$LOG/p2f_executed_path_final.txt"
  cat "$LOG"/samples/*_bimodal_active_path.txt > "$LOG/p2f_active_path.log" 2>/dev/null || true
  cat "$LOG"/samples/*_bimodal_executed_path.txt > "$LOG/p2f_executed_path.log" 2>/dev/null || true

  set +e
  ros2 topic list 2>/dev/null | grep -E "^/cmd_vel$|^/mavros/|^/fmu/|^/actuator/|^/offboard_control_mode$|^/trajectory_setpoint$" > "$LOG/p2f_no_real_control_topic_check.txt"
  set -e
}

if [ "$build_rc" -eq 0 ]; then
  run_long_phase "$MODE"
else
  echo "Build failed; long run not launched." > "$LOG/p2f_no_real_control_topic_check.txt"
fi

cleanup_pids
trap - EXIT
trap - INT TERM

python3 - "$LOG" "$DURATION" "$MODE" "$INPUT_TOPIC" "$LONG_RUN_600S_COMPLETED" "$build_rc" "$GIT_BRANCH" "$GIT_COMMIT_BEFORE" <<'PY'
import csv
import hashlib
import math
import re
import sys
from pathlib import Path

log = Path(sys.argv[1])
requested_duration = float(sys.argv[2])
mode = sys.argv[3]
input_topic = sys.argv[4]
long_run_600s_completed = sys.argv[5]
build_rc = int(sys.argv[6])
git_branch = sys.argv[7]
git_commit_before = sys.argv[8]

def read(name):
    p = log / name
    return p.read_text(errors='ignore') if p.exists() else ''

def rows(name):
    p = log / name
    if not p.exists():
        return []
    with p.open(newline='', encoding='utf-8') as f:
        return list(csv.DictReader(f))

def report_value(text, key, default='FAIL'):
    for line in text.splitlines():
        if line.startswith(key + '='):
            return line.split('=', 1)[1].strip()
    return default

def vals(text, key):
    out = []
    for m in re.finditer(rf'{re.escape(key)}=([A-Za-z0-9_.:/()+,-]+)', text):
        out.append(m.group(1).strip('",'))
    return out

def fvals(text, key):
    out = []
    for value in vals(text, key):
        try:
            out.append(float(value.strip('(),')))
        except Exception:
            pass
    return out

def last_int(text, key, default=0):
    values = fvals(text, key)
    return int(values[-1]) if values else default

def first_int(text, key, default=0):
    values = fvals(text, key)
    return int(values[0]) if values else default

def last_float(text, key, default=0.0):
    values = fvals(text, key)
    return float(values[-1]) if values else default

def first_float(text, key, default=0.0):
    values = fvals(text, key)
    return float(values[0]) if values else default

def row_float(row, key, default=0.0):
    try:
        return float(row.get(key, default) or default)
    except Exception:
        return default

def passfail(condition):
    return 'PASS' if condition else 'FAIL'

def average_rate(text):
    m = re.search(r'average rate: ([0-9.]+)', text)
    return float(m.group(1)) if m else 0.0

build_report = read('build_report.md')
sensor_text = read('p2f_sensor_input_status.log')
map_text = read('p2f_map_metrics.log')
backend_text = read('p2f_map_backend_status.log')
active_mode_text = read('p2f_active_mode.log')
tf_text = read('p2f_tf_snapshot.txt')
visual_text = read('p2f_visual_topics_ready_report.md')
node_end = read('p2f_node_snapshot_end.txt')
topic_end = read('p2f_topic_snapshot_end.txt')
cleanup_text = read('p2f_process_cleanup_check.txt')
forbidden_text = read('p2f_no_real_control_topic_check.txt').strip()
points_rate_text = read('p2f_points_rate.txt')
map3d_rate_text = read('p2f_map3d_rate.txt')
points_once = read('p2f_bimodal_points_once.txt')
map3d_once = read('p2f_map3d_once.txt')
active_path_text = read('p2f_active_path.log') + '\n' + read('p2f_active_path_final.txt')
executed_path_text = read('p2f_executed_path.log') + '\n' + read('p2f_executed_path_final.txt')

map_rows = rows('p2e_octomap_map_metrics.csv')
eff_rows = rows('p2e_octomap_exploration_efficiency.csv')
path_rows = rows('e2e_paths.csv')
odom_rows = rows('e2e_odom.csv')
goal_rows = rows('e2e_goals.csv')
mode_rows = rows('e2e_mode.csv')

external_start = first_int(sensor_text, 'external_cloud_received_count', 0)
external_end = last_int(sensor_text, 'external_cloud_received_count', 0)
output_start = first_int(sensor_text, 'output_cloud_published_count', 0)
output_end = last_int(sensor_text, 'output_cloud_published_count', 0)
input_timeout_count = last_int(sensor_text, 'input_timeout_count', 0)
fallback_active_total_sec = 'UNKNOWN'
dropped_cloud_count = last_int(sensor_text, 'dropped_cloud_count', 0)

occ_values = []
cov_values = []
if map_rows:
    for r in map_rows:
        occ_values.append(row_float(r, 'occupied_voxel_count', 0.0))
        cov_values.append(row_float(r, 'coverage_proxy', 0.0))
else:
    occ_values = fvals(map_text, 'occupied_voxel_count')
    cov_values = fvals(map_text, 'coverage_proxy')
occ_start = int(occ_values[0]) if occ_values else 0
occ_end = int(occ_values[-1]) if occ_values else 0
cov_start = float(cov_values[0]) if cov_values else 0.0
cov_end = float(cov_values[-1]) if cov_values else 0.0

points_rate = average_rate(points_rate_text)
if points_rate <= 0.0 and output_end > output_start:
    points_rate = (output_end - output_start) / max(requested_duration, 1.0)
map3d_rate = average_rate(map3d_rate_text)

active_rows = [r for r in path_rows if r.get('source') == 'active']
active_path_count = len(active_rows)
active_hashes = []
same_hash_max = 0.0
last_hash = None
last_hash_start = None
for r in active_rows:
    h = f'{r.get("pose_count", "")}:{round(row_float(r, "path_length", 0.0), 2)}'
    t = row_float(r, 'timestamp', 0.0)
    active_hashes.append(h)
    if h != last_hash:
        if last_hash is not None and last_hash_start is not None:
            same_hash_max = max(same_hash_max, t - last_hash_start)
        last_hash = h
        last_hash_start = t
if active_rows and last_hash_start is not None:
    same_hash_max = max(same_hash_max, row_float(active_rows[-1], 'timestamp', 0.0) - last_hash_start)
active_path_unique_hash_count = len(set(active_hashes))
active_path_update_count = active_path_count

odom_total_distance = 0.0
if odom_rows:
    odom_total_distance = max(row_float(r, 'total_distance', 0.0) for r in odom_rows)
executed_path_length = odom_total_distance
executor_text = '\n'.join(p.read_text(errors='ignore') for p in sorted((log / 'samples').glob('*_bimodal_fake_executor_status.txt')))
if executor_text:
    executed_path_length = max(executed_path_length, last_float(executor_text, 'total_distance', 0.0))
executed_path_count = executed_path_text.count('poses:') or len(odom_rows)

mode_values = [r.get('mode', '').strip() for r in mode_rows if r.get('mode', '').strip()]
active_mode_switch_count = sum(1 for a, b in zip(mode_values, mode_values[1:]) if a != b)
air_goal_count = sum(1 for r in goal_rows if r.get('source') == 'air')
ground_goal_count = sum(1 for r in goal_rows if r.get('source') == 'ground')
path_switch_count = active_path_unique_hash_count

map_growth_stall_max_sec = 'UNKNOWN'
if map_rows:
    last_growth_t = None
    max_stall = 0.0
    prev = None
    for r in map_rows:
        t = row_float(r, 'timestamp', 0.0)
        key = (row_float(r, 'occupied_voxel_count', 0.0), row_float(r, 'coverage_proxy', 0.0))
        if prev is None or key != prev:
            if last_growth_t is not None:
                max_stall = max(max_stall, t - last_growth_t)
            last_growth_t = t
            prev = key
    if last_growth_t is not None:
        max_stall = max(max_stall, row_float(map_rows[-1], 'timestamp', 0.0) - last_growth_t)
    map_growth_stall_max_sec = f'{max_stall:.3f}'

frame_text = points_once + '\n' + map3d_once
frame_match = re.search(r'frame_id:\s*([A-Za-z0-9_/.-]+)', frame_text)
points_frame = frame_match.group(1).strip('"\'') if frame_match else 'UNKNOWN'

forbidden_lines = [line for line in forbidden_text.splitlines() if line.strip()]
forbidden_count = len(forbidden_lines)
forbidden_list = ','.join(forbidden_lines) if forbidden_lines else 'NONE'

map_build = report_value(build_report, 'map_build')
air_build = report_value(build_report, 'air_build')
ground_build = report_value(build_report, 'ground_build')
p2f_runner_build = report_value(build_report, 'p2f_runner_build')
cleanup_pass = report_value(cleanup_text, 'cleanup_pass')
remaining_owned_process_count = int(report_value(cleanup_text, 'remaining_owned_process_count', '0') or 0)

rviz_fixed_frame_ready = report_value(tf_text, 'RVIZ_FIXED_FRAME_READY')
visual_topics_ready = report_value(visual_text, 'VISUAL_TOPICS_READY_FOR_RVIZ')
tf_tree_ready = passfail(
    'TF2_ECHO_MAP_BASE_LINK=PASS' in tf_text and
    'TF_STATIC_MESSAGE_CAPTURED=PASS' in tf_text and
    ('camera_link' in read('p2f_tf_guard_status_once.txt') or '/tf_static' in topic_end) and
    ('lidar_link' in read('p2f_tf_guard_status_once.txt') or '/tf_static' in topic_end)
)

map_frame_exists = passfail('map' in tf_text or 'map' in read('p2f_tf_guard_status_once.txt'))
odom_frame_exists = passfail('odom' in tf_text or 'odom' in read('p2f_tf_guard_status_once.txt'))
base_link_frame_exists = passfail('base_link' in tf_text or 'base_link' in read('p2f_tf_guard_status_once.txt'))
camera_link_frame_exists = passfail('camera_link' in read('p2f_tf_guard_status_once.txt') or 'camera_link' in tf_text)
lidar_link_frame_exists = passfail('lidar_link' in read('p2f_tf_guard_status_once.txt') or 'lidar_link' in tf_text)

long_run_started = passfail('map_p2f_runtime.log' in '\n'.join(p.name for p in log.iterdir()) and build_rc == 0)
long_run_completed = passfail(read('p2f_topic_snapshot_end.txt').strip() != '' and build_rc == 0)
duration_sec = requested_duration if long_run_completed == 'PASS' else 0.0

external_delta = max(0, external_end - external_start)
output_delta = max(0, output_end - output_start)
bimodal_points_captured = passfail(output_delta > 0 or 'stamp:' in points_once or '/bimodal/points' in topic_end)
last_backend_input_age_sec = last_float(map_text, 'last_input_age_sec', 999999.0)
external_pointcloud_long_run = passfail(
    mode == 'external_pointcloud_long_run' and external_delta > 0 and output_delta > 0 and
    points_rate > 0.0 and input_timeout_count == 0 and last_backend_input_age_sec < 30.0
)
virtual_regression_long_run = 'PASS' if mode == 'virtual_regression_long_run' and bimodal_points_captured == 'PASS' else 'NOT_RUN'
if mode != 'virtual_regression_long_run':
    virtual_regression_long_run = 'NOT_RUN'

map_backend_status_captured = passfail('backend_mode=octomap_style_voxel' in backend_text)
map_metrics_captured = passfail(bool(map_rows) or 'coverage_proxy=' in map_text)
octomap_backend_node_running = passfail('octomap_pointcloud_backend_node' in node_end)
occupied_increased = passfail(occ_end > occ_start)
coverage_increased = passfail(cov_end > cov_start)
map_growth_long_run = passfail(
    octomap_backend_node_running == 'PASS' and map_metrics_captured == 'PASS' and
    occupied_increased == 'PASS' and coverage_increased == 'PASS'
)
try:
    if float(map_growth_stall_max_sec) > 120.0:
        map_growth_long_run = 'FAIL'
except Exception:
    pass

active_path_captured = passfail(active_path_count > 0 or 'poses:' in active_path_text)
executed_path_captured = passfail(executed_path_count > 0 or 'poses:' in executed_path_text)
planner_chain_long_run = passfail(
    active_path_captured == 'PASS' and executed_path_captured == 'PASS' and
    odom_total_distance > 0.0 and executed_path_length > 0.0 and
    'air_exploration_stub_node' in node_end and 'ground_3d_frontier_node' in node_end and
    'bimodal_mode_mux_node' in node_end
)
active_mode_captured = passfail(bool(mode_values) or bool(active_mode_text.strip()))

if active_path_captured != 'PASS':
    path_stability_long_run = 'FAIL'
elif active_path_unique_hash_count > 1:
    path_stability_long_run = 'PASS'
elif odom_total_distance > 0.0:
    path_stability_long_run = 'PASS_PARTIAL'
else:
    path_stability_long_run = 'FAIL'

no_real_control_topic = passfail(forbidden_count == 0)
p1c_regression_guard = passfail(external_pointcloud_long_run == 'PASS' and bimodal_points_captured == 'PASS')
p2e_regression_guard = passfail(map_growth_long_run == 'PASS' and planner_chain_long_run == 'PASS')

required = [
    map_build, air_build, ground_build, p2f_runner_build, long_run_started, long_run_completed,
    external_pointcloud_long_run if mode == 'external_pointcloud_long_run' else 'PASS',
    map_growth_long_run, planner_chain_long_run, rviz_fixed_frame_ready, visual_topics_ready,
    tf_tree_ready, cleanup_pass, no_real_control_topic,
]
final_baseline_gate = 'PASS' if all(v == 'PASS' for v in required) and path_stability_long_run in ('PASS', 'PASS_PARTIAL') and duration_sec >= 300 else 'FAIL'
result = final_baseline_gate
if final_baseline_gate == 'PASS' and path_stability_long_run == 'PASS_PARTIAL':
    result = 'PASS_PARTIAL'
    final_baseline_gate = 'PASS_PARTIAL'

failure = 'NONE'
reason = 'No remaining P2F failure.'
if result == 'FAIL':
    if no_real_control_topic != 'PASS':
        failure, reason = 'SAFETY_FAIL', 'Forbidden real control topic appeared in the runtime ROS graph.'
    elif any(v != 'PASS' for v in [map_build, air_build, ground_build, p2f_runner_build]):
        failure, reason = 'BUILD_FAIL', 'One or more workspaces failed to build.'
    elif long_run_started != 'PASS' or long_run_completed != 'PASS':
        failure, reason = 'LONG_RUN_LAUNCH_FAIL', 'The long-run validation did not start or complete.'
    elif external_pointcloud_long_run != 'PASS' and mode == 'external_pointcloud_long_run':
        failure, reason = 'SENSOR_INPUT_STALE', 'External PointCloud2 bridge did not keep receiving/publishing clouds.'
    elif bimodal_points_captured != 'PASS':
        failure, reason = 'BIMODAL_POINTS_DROPPED', '/bimodal/points was not captured.'
    elif map_growth_long_run != 'PASS':
        failure, reason = 'MAP_NOT_GROWING', 'OctoMap-style metrics did not grow during the run.'
    elif map_metrics_captured != 'PASS':
        failure, reason = 'MAP_METRICS_STALE', '/bimodal/map_metrics was not captured.'
    elif planner_chain_long_run != 'PASS':
        failure, reason = 'PLANNER_CHAIN_BROKEN', 'Active/executed path or fake executor metrics were missing.'
    elif path_stability_long_run == 'FAIL':
        failure, reason = 'ACTIVE_PATH_STALE', 'Active path was missing or stale without odom progress.'
    elif tf_tree_ready != 'PASS':
        failure, reason = 'TF_REGRESSION', 'TF readiness check failed.'
    elif visual_topics_ready != 'PASS':
        failure, reason = 'RVIZ_TOPIC_REGRESSION', 'One or more required visual topics were missing.'
    elif cleanup_pass != 'PASS':
        failure, reason = 'CLEANUP_FAIL', 'Owned long-run processes were not fully cleaned.'
    else:
        failure, reason = 'UNKNOWN_FAIL', 'P2F failed for an unclassified reason.'
elif result == 'PASS_PARTIAL':
    failure = 'NONE'
    reason = 'No remaining P2F failure; path stability is PASS_PARTIAL because the active path did not produce many unique hashes while odom/executed path continued.'

fields = {
    'project_stage': 'P2_END_TO_END_BIMODAL_FLOW_VALIDATION',
    'current_substage': 'P2F_LONG_RUN_STABILITY_AND_FINAL_BASELINE_GATE',
    'work_done': 'Validated long-run external PointCloud2 to OctoMap-backed Air/Ground planning baseline and generated final baseline gate logs',
    'work_not_done': 'No FUEL, no TARE, no GBPlanner, no real control, no nvblox, no RTAB-Map, no real octomap_server',
    'root': '/home/nuaa/ZHY/3DPlanner_FULL',
    'log_dir': str(log),
    'git_branch': git_branch,
    'git_commit_before': git_commit_before,
    'git_commit_after': 'NONE',
    'map_build': map_build,
    'air_build': air_build,
    'ground_build': ground_build,
    'p2f_runner_build': p2f_runner_build,
    'p1c_regression_guard': p1c_regression_guard,
    'p2e_regression_guard': p2e_regression_guard,
    'selected_input_mode': 'external_pointcloud' if mode == 'external_pointcloud_long_run' else 'virtual',
    'selected_input_topic': input_topic,
    'bridge_output_topic': '/bimodal/points',
    'long_run_started': long_run_started,
    'long_run_completed': long_run_completed,
    'duration_sec': f'{duration_sec:.3f}',
    'long_run_600s_completed': long_run_600s_completed,
    'external_pointcloud_long_run': external_pointcloud_long_run if mode == 'external_pointcloud_long_run' else 'NOT_RUN',
    'virtual_regression_long_run': virtual_regression_long_run,
    'external_cloud_received_count_start': str(external_start),
    'external_cloud_received_count_end': str(external_end),
    'external_cloud_received_delta': str(external_delta),
    'output_cloud_published_count_start': str(output_start),
    'output_cloud_published_count_end': str(output_end),
    'output_cloud_published_delta': str(output_delta),
    'bimodal_points_captured': bimodal_points_captured,
    'bimodal_points_rate_avg_hz': f'{points_rate:.3f}',
    'input_timeout_count': str(input_timeout_count),
    'fallback_active_total_sec': fallback_active_total_sec,
    'last_backend_input_age_sec': f'{last_backend_input_age_sec:.3f}',
    'octomap_backend_node_running': octomap_backend_node_running,
    'map_backend_status_captured': map_backend_status_captured,
    'map_metrics_captured': map_metrics_captured,
    'occupied_voxel_count_start': str(occ_start),
    'occupied_voxel_count_end': str(occ_end),
    'occupied_voxel_count_delta': str(occ_end - occ_start),
    'occupied_voxel_count_increased': occupied_increased,
    'coverage_proxy_start': f'{cov_start:.6f}',
    'coverage_proxy_end': f'{cov_end:.6f}',
    'coverage_proxy_delta': f'{cov_end - cov_start:.6f}',
    'coverage_proxy_increased': coverage_increased,
    'map_growth_long_run': map_growth_long_run,
    'map_growth_stall_max_sec': map_growth_stall_max_sec,
    'active_path_captured': active_path_captured,
    'active_path_count': str(active_path_count),
    'active_path_update_count': str(active_path_update_count),
    'active_path_unique_hash_count': str(active_path_unique_hash_count),
    'active_path_same_hash_max_duration_sec': f'{same_hash_max:.3f}' if active_rows else 'UNKNOWN',
    'executed_path_captured': executed_path_captured,
    'executed_path_count': str(executed_path_count),
    'executed_path_length_m': f'{executed_path_length:.3f}',
    'odom_total_distance_m': f'{odom_total_distance:.3f}',
    'planner_chain_long_run': planner_chain_long_run,
    'path_stability_long_run': path_stability_long_run,
    'active_mode_captured': active_mode_captured,
    'active_mode_switch_count': str(active_mode_switch_count),
    'air_goal_count': str(air_goal_count),
    'ground_goal_count': str(ground_goal_count),
    'rviz_fixed_frame_ready': rviz_fixed_frame_ready,
    'visual_topics_ready': visual_topics_ready,
    'tf_tree_ready': tf_tree_ready,
    'cleanup_pass': cleanup_pass,
    'remaining_owned_process_count': str(remaining_owned_process_count),
    'no_real_control_topic': no_real_control_topic,
    'forbidden_topic_detected_count': str(forbidden_count),
    'forbidden_topic_list': forbidden_list,
    'final_baseline_gate': final_baseline_gate,
    'P2F_LONG_RUN_STABILITY': result,
    'changed_files': 'scripts/run_p2f_long_run_stability_validation.sh,test-log/20260701_163208_p2f_long_run_stability/p2f_chain_audit.md',
    'local_commit_created': 'PENDING',
    'main_result_summary': 'Shared 3D map plus external PointCloud2 input long-run baseline gate completed.' if result != 'FAIL' else 'P2F baseline gate failed; see remaining_failure_class.',
    'remaining_failure_class': failure,
    'remaining_failure_reason': reason,
    'summary_report': str(log / 'p2f_long_run_summary.md'),
    'debug_package': '/home/nuaa/ZHY/3DPlanner_FULL/latest_p2f_long_run_stability_package.tar.gz',
    'recommended_next_prompt_type': 'P3A_AIR_FUEL_WRAPPER_AND_P4A_GROUND_3D_WRAPPER_PLANNING' if result != 'FAIL' else 'FIX_P2F_LONG_RUN_STABILITY',
    'next_stage_explanation': 'The shared map, external PointCloud2 input, planners, fake executor, TF, RViz topics, cleanup, and safety gate are stable enough for planner wrapper planning.' if result != 'FAIL' else 'Fix the P2F failure class before entering real planner wrapper work.',
}

with (log / 'p2f_long_run_metrics.csv').open('w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(['metric', 'value'])
    for key in [
        'duration_sec', 'external_cloud_received_count_start', 'external_cloud_received_count_end',
        'external_cloud_received_delta', 'output_cloud_published_count_start',
        'output_cloud_published_count_end', 'output_cloud_published_delta',
        'bimodal_points_rate_avg_hz', 'input_timeout_count', 'last_backend_input_age_sec',
        'occupied_voxel_count_start',
        'occupied_voxel_count_end', 'occupied_voxel_count_delta', 'coverage_proxy_start',
        'coverage_proxy_end', 'coverage_proxy_delta', 'active_path_count',
        'active_path_update_count', 'active_path_unique_hash_count',
        'active_path_same_hash_max_duration_sec', 'executed_path_count',
        'executed_path_length_m', 'odom_total_distance_m', 'active_mode_switch_count',
        'air_goal_count', 'ground_goal_count', 'remaining_owned_process_count',
        'forbidden_topic_detected_count',
    ]:
        writer.writerow([key, fields[key]])

with (log / 'p2f_long_run_summary.md').open('w', encoding='utf-8') as f:
    f.write('# P2F Long Run Stability Summary\n\n')
    f.write('当前阶段：P2F_LONG_RUN_STABILITY_AND_FINAL_BASELINE_GATE。\n\n')
    f.write('本轮完成：基于 P1C external PointCloud2 输入链路进行了长时间稳定性验证，覆盖 bridge、octomap_style_voxel backend、Air/Ground planner、mode mux、fake executor、TF/RViz topics、cleanup 和 no_real_control_topic。\n\n')
    f.write('本轮未做：未接真实飞控、未接 FUEL/TARE/GBPlanner、未切换 nvblox/RTAB-Map、未接真实 octomap_server、未大改 Air/Ground 核心算法。\n\n')
    f.write(f'长测模式：{mode}，请求时长 {requested_duration:.0f}s，完成状态 {result}。\n\n')
    f.write(f'PointCloud2 输入：external_cloud_received_count {external_start} -> {external_end}，output_cloud_published_count {output_start} -> {output_end}，/bimodal/points rate {points_rate:.3f} Hz。\n\n')
    f.write(f'地图增长：occupied_voxel_count {occ_start} -> {occ_end}，coverage_proxy {cov_start:.6f} -> {cov_end:.6f}。\n\n')
    f.write(f'规划链路：active_path_count={active_path_count}，executed_path_length_m={executed_path_length:.3f}，odom_total_distance_m={odom_total_distance:.3f}，mode_switch_count={active_mode_switch_count}。\n\n')
    f.write(f'RViz/TF：rviz_fixed_frame_ready={rviz_fixed_frame_ready}，visual_topics_ready={visual_topics_ready}，tf_tree_ready={tf_tree_ready}。\n\n')
    f.write(f'生命周期：cleanup_pass={cleanup_pass}，remaining_owned_process_count={remaining_owned_process_count}。\n\n')
    f.write(f'安全：no_real_control_topic={no_real_control_topic}，forbidden_topic_detected_count={forbidden_count}。\n\n')
    f.write(f'最终 gate：final_baseline_gate={final_baseline_gate}，P2F_LONG_RUN_STABILITY={result}。\n\n')
    f.write(f'下一阶段建议：{fields["recommended_next_prompt_type"]}。{fields["next_stage_explanation"]}\n')

with (log / 'p2f_acceptance_report.md').open('w', encoding='utf-8') as f:
    f.write('# P2F Acceptance Report\n\n')
    for key, value in fields.items():
        f.write(f'{key}={value}\n')

print('B3D_P2F_LONG_RUN_STABILITY_SUMMARY')
for key, value in fields.items():
    print(f'{key}={value}')
PY

tar -czf "$ROOT/latest_p2f_long_run_stability_package.tar.gz" -C "$(dirname "$LOG")" "$(basename "$LOG")"
cat "$LOG/p2f_acceptance_report.md"
